### ISSUE TITLE
drop-in replacement for istanbul? 

### ISSUE THREAD

**Issue by nelsonic** [ambitioninc/babel-istanbul#51]
@jmcriffey which test frameworks have you tried with `babel-istanbul` ?

we use [`tape`](https://github.com/substack/tape) but when attempting to run our tests using `babel-istanbul` we get the following error: `SyntaxError: Unexpected reserved word` 

We are running the `bable-istanbul` command using a *relative* path as we *prefer* not install node modules *globally*, thus our `test` command is: 
```sh
./node_modules/.bin/babel-istanbul cover ./node_modules/tape/bin/tape ./test/index.js
```
Please see: https://travis-ci.org/dwyl/ampl/builds/103671132#L278

**Comment by jmcriffey** [comment]
I've mostly use `mocha`, but your testing framework should not affect the coverage unless you are spawning new processes to run tests.

The module `babel-istanbul` simply compiles files for instrumentation, so you decide how you are going to compile your tests for running. Have you successfully run those same tests without coverage? How are you compiling those test files?

I have always run my tests with `babel-node` instead of `node` like so:

```
./node_modules/.bin/babel-node ./node_modules/.bin/babel-istanbul cover test_command_here
```

**Comment by nelsonic** [comment]
@jmcriffey trying that now. (*thanks for speedy reply*!)

**Comment by nelsonic** [comment]
@jmcriffey appear to be working... https://travis-ci.org/dwyl/ampl/builds/103683244#L297
thanks again for getting back to us!
anyone else using substack's tape for their tests, the command we used is: 
```js
./node_modules/.bin/babel-node ./node_modules/.bin/babel-istanbul cover ./node_modules/tape/bin/tape ./test/
```
